### ISSUE TITLE
rv32_3stage build failure on Ubuntu 17.04

### ISSUE THREAD

**Issue by sshimomu2k2** [ucb-bar/riscv-sodor#29]
Hi,

I'm trying to build following the build instructions, and the emulator build failed with the following messages; Could you please let me know where/which file to look into?
From the message I can see it's somewhere in risc-v code itself or Chisel, but there is no emulator/rv32_3stages/generated-src path/file & no other informative message, so I don't know where to look into.

I use Ubuntu 17.04 and created a fresh VM session just for this, then exactly followed the instruction on the page.

[ Error messages ]
<...>
make[1]: Leaving directory '/home/sshimomu/riscv-sodor/emulator/rv32_2stage'
make -C emulator/rv32_3stage/
make[1]: Entering directory '/home/sshimomu/riscv-sodor/emulator/rv32_3stage'
cd /home/sshimomu/riscv-sodor && java -Xmx4096M -Xss8M -XX:MaxPermSize=128M -jar /home/sshimomu/riscv-sodor/sbt/sbt-launch.jar  "project rv32_3stage" "run -td emulator/rv32_3stage/generated-src"
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
[info] Loading project definition from /home/sshimomu/riscv-sodor/project
[info] Set current project to riscv-sodor (in build file:/home/sshimomu/riscv-sodor/)
[info] Set current project to rv32_3stage (in build file:/home/sshimomu/riscv-sodor/)
[info] Running Sodor.elaborate -td emulator/rv32_3stage/generated-src
[info] [0.005] Elaborating design...
[error] (run-main) chisel3.core.Binding$ExpectedChiselTypeException: 'chisel3.core.UInt@2a9' must be a Chisel type, not hardware
chisel3.core.Binding$ExpectedChiselTypeException: 'chisel3.core.UInt@2a9' must be a Chisel type, not hardware
    at chisel3.core.requireIsChiselType$.apply(Binding.scala:41)
    at chisel3.core.Output$.apply(Data.scala:176)
    at Sodor.CtrlSignals.<init>(cpath.scala:34)
    at Sodor.CpathIo.<init>(cpath.scala:46)
    at Sodor.CtlPath.<init>(cpath.scala:53)
    at Sodor.Core$$anonfun$2.apply(core.scala:26)
    at Sodor.Core$$anonfun$2.apply(core.scala:26)
    at chisel3.core.Module$.do_apply(Module.scala:45)
    at Sodor.Core.<init>(core.scala:26)
[info] Set current project to rv32_3stage (in build file:/home/sshimomu/riscv-sodor/)
[info] Running Sodor.elaborate -td emulator/rv32_3stage/generated-src
[info] [0.005] Elaborating design...
[error] (run-main) chisel3.core.Binding$ExpectedChiselTypeException: 'chisel3.core.UInt@2a9' must be a Chisel type, not hardware
chisel3.core.Binding$ExpectedChiselTypeException: 'chisel3.core.UInt@2a9' must be a Chisel type, not hardware
    at chisel3.core.requireIsChiselType$.apply(Binding.scala:41)
    at chisel3.core.Output$.apply(Data.scala:176)
    at Sodor.CtrlSignals.<init>(cpath.scala:34)
    at Sodor.CpathIo.<init>(cpath.scala:46)
    at Sodor.CtlPath.<init>(cpath.scala:53)
    at Sodor.Core$$anonfun$2.apply(core.scala:26)
    at Sodor.Core$$anonfun$2.apply(core.scala:26)
    at chisel3.core.Module$.do_apply(Module.scala:45)
    at Sodor.Core.<init>(core.scala:26)
[info] Set current project to rv32_3stage (in build file:/home/sshimomu/riscv-sodor/)
[info] Running Sodor.elaborate -td emulator/rv32_3stage/generated-src
[info] [0.005] Elaborating design...
[error] (run-main) chisel3.core.Binding$ExpectedChiselTypeException: 'chisel3.core.UInt@2a9' must be a Chisel type, not hardware
chisel3.core.Binding$ExpectedChiselTypeException: 'chisel3.core.UInt@2a9' must be a Chisel type, not hardware
    at chisel3.core.requireIsChiselType$.apply(Binding.scala:41)
    at chisel3.core.Output$.apply(Data.scala:176)
    at Sodor.CtrlSignals.<init>(cpath.scala:34)
    at Sodor.CpathIo.<init>(cpath.scala:46)
    at Sodor.CtlPath.<init>(cpath.scala:53)
    at Sodor.Core$$anonfun$2.apply(core.scala:26)
    at Sodor.Core$$anonfun$2.apply(core.scala:26)
    at chisel3.core.Module$.do_apply(Module.scala:45)
    at Sodor.Core.<init>(core.scala:26)
$>

**Comment by codelec** [comment]
Hey @sshimomu2k2 there seem to have been changes in chisel3 due to which you are facing this issue. For now could you please make changes on this line https://github.com/ucb-bar/riscv-sodor/blob/master/src/rv32_3stage/cpath.scala#L34 
replace "M_X.getWidth" with "1.W"
there will be a fix for this soon

**Comment by sshimomu2k2** [comment]
Thanks, the build completes now!
